# Generated by Django 4.2.14 on 2024-08-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerprofile',
            options={'permissions': [('premium_account', 'User has access to premium features')]},
        ),
    ]
