# Generated by Django 4.2.14 on 2024-08-13 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0002_alter_playerprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='desired_wn8',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
