# Generated by Django 4.2.14 on 2024-08-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0003_playerprofile_desired_wn8'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='premium_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
