# Generated by Django 4.2.14 on 2024-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0005_playerprofile_battles_playerprofile_current_wn8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='current_wn8',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
