# Generated by Django 5.0.7 on 2024-07-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=100)),
                ('wg_tank_id', models.IntegerField()),
                ('tier', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('exp_def', models.FloatField(null=True)),
                ('exp_spot', models.FloatField(null=True)),
                ('exp_damage', models.FloatField(null=True)),
                ('exp_winrate', models.FloatField(null=True)),
            ],
        ),
    ]
