# Generated by Django 4.2.14 on 2024-08-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stat_module', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='exp_frag',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battles', models.IntegerField(default=0)),
                ('wn8', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stat_module.player')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetailedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_battles', models.IntegerField(default=0)),
                ('tank_wn8', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stat_module.player')),
                ('tank_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stat_module.tank')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
