# Generated by Django 4.2.14 on 2024-08-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_module', '0003_tank_exp_frag_playerstats_detailedstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailedstats',
            old_name='tank_id',
            new_name='tank',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='player_id',
            new_name='player',
        ),
    ]
