# Generated by Django 4.2.14 on 2024-08-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_module', '0004_rename_tank_id_detailedstats_tank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='big_icon',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='contour_icon',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='small_icon',
            field=models.URLField(null=True),
        ),
    ]
