# Generated by Django 4.2.14 on 2024-08-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_module', '0005_tank_big_icon_tank_contour_icon_tank_small_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedstats',
            name='actual',
            field=models.BooleanField(default=True),
        ),
    ]
