# Generated by Django 4.2.14 on 2024-08-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_module', '0007_playerstats_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(unique=True),
        ),
    ]
