# Generated by Django 4.2.14 on 2024-08-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_module', '0008_alter_player_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedstats',
            name='avg_damage',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='detailedstats',
            name='avg_def',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='detailedstats',
            name='avg_frag',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='detailedstats',
            name='avg_spot',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='detailedstats',
            name='avg_winrate',
            field=models.FloatField(default=0, null=True),
        ),
    ]
